CREATE TABLE IF NOT EXISTS `demo_media_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `demo` VARCHAR(64) NOT NULL,
  `imgs` JSON NOT NULL,
  `sizes` JSON NOT NULL,
  `blacklist` JSON NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_demo_media_config_demo` (`demo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
